<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Burnout.$([System.Text.RegularExpressions.Regex]::Replace("$(MSBuildProjectName)", ".Abstractions$", ""))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
	</ItemGroup>
</Project>
